backend:
  name: github
  repo: iyansanjaya/lumy # Path to your GitHub repository
  auth_scope: repo # this is needed to fork the private repo
  open_authoring: true
  branch: master # Branch to update (optional; defaults to master)
  commit_messages:
    create: Create {{collection}} “{{slug}} - {{author-login}}”
    update: Update {{collection}} “{{slug}} - {{author-login}}”
    delete: Delete {{collection}} “{{slug}} - {{author-login}}”
    uploadMedia: Upload “{{path}} - {{author-login}}”
    deleteMedia: Delete “{{path}} - {{author-login}}”
    openAuthoring: '{{message}}'

# media_folder: static/img
media_library:
  name: uploadcare
  config:
    publicKey: YOUR_UPLOADCARE_PUBLIC_KEY
public_folder: /img
publish_mode: editorial_workflow
logo_url: https://lumy.li/img/logo.webp

collections:
  - name: "shortlink" # Used in routes, e.g., /admin/collections/blog
    label: "Shortlink" # Used in the UI
    folder: "/content/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Short Link", name: "url", widget: "string", hint: "Contoh pengisian shortlink: **iyan** (tidak ada batas jumlah huruf). *Jangan gunakan lumy.li lagi di depan shortlink*, cukup masukan shortlink yang ingin Anda gunakan. Nantinya jika shortlink sudah ditinjau, maka secara otomatis akan menjadi *lumy.li/iyan*."}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Link yang dituju", name: "linktogo", widget: "string", hint: "Contoh link yang dituju: https://instagram.com/iyannsanjaya | Waktu proses peninjuan paling lama 1x24 jam."}
      - { label: "Author", name: "author", widget: "hidden", default: "" }