backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: "shortlink" # Used in routes, e.g., /admin/collections/blog
    label: "Shortlink" # Used in the UI
    folder: "/content/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short Link", name: "url", widget: "string"}
      - {label: "Redirect Link", name: "linktogo", widget: "string"}