name = 'Lumisas'
license = 'MIT'
licenselink = 'https://github.com/iyansanjaya/lumy/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/iyansanjaya/lumy'

# Taxonomy terms
tags = ['company']
features = ['shortlink', 'unlimited', 'free']

# If the theme has a single author
[author]
  name = 'Iyan Sanjaya'
  homepage = 'https://iyansanjaya.com'
